### ISSUE TITLE
 License

### ISSUE THREAD

**Issue by accraze** [discogs/pymongo-job-queue#1]
need to choose a license.... which one makes the most sense?
http://choosealicense.com/

**Comment by accraze** [comment]
@kevinsl.... since you wrote some of the initial `JobQueue` code, I wanted to get your opinion on which license we should use.

i'm in favor of either [MIT](http://choosealicense.com/licenses/mit/), [BSD/ISC](http://choosealicense.com/licenses/isc/) or the [Unlicense](http://choosealicense.com/licenses/unlicense/).... but we could also release it under [Pizza-Ware](http://www.calculate-linux.org/packages/licenses/PIZZA-WARE)

**Comment by accraze** [comment]
nevermind... just gonna use the same License from our other repos (i.e. https://raw.githubusercontent.com/discogs/hdf2json/master/LICENSE)

**Comment by accraze** [comment]
Re-opening this issue, after thinking about it... since `pymongo` is released under Apache, using MIT or Apache makes the most sense to me instead of than the standard all rights reserved license on our other repos...any objections?

**Comment by kevinsl** [comment]
I don't know the details of all open source licenses. But I would go with whatever is the least restrictive. thanks.

**Comment by accraze** [comment]
cool.. MIT it is....
